name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  animate_do: ^3.0.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  go_router: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
